services:
  client:
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      - ./client:/client
    stdin_open: true
    tty: true
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: ./build/package/Dockerfile
    ports:
      - "${API_PORT}:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_APP_USER: ${POSTGRES_APP_USER}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
      DOCKER_HOSTNAME: host.docker.internal
      AWS_REGION: ${AWS_REGION}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
    volumes:
      - ./api:/api
    tty: true
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  client:
  api:
  db:
