// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: test_truncate.sql

package model

import (
	"context"
)

const truncateAllTables = `-- name: TruncateAllTables :exec
TRUNCATE TABLE
  app.todos
CASCADE
`

func (q *Queries) TruncateAllTables(ctx context.Context, db DBTX) error {
	_, err := db.Exec(ctx, truncateAllTables)
	return err
}
